# This configuration uses the kitchen-ec2 plugin
# https://github.com/test-kitchen/kitchen-ec2
#
# The following environmental variables are required:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_SSH_KEY_ID
# - AWS_SUBNET_ID
# - AWS_SECURITY_GROUP_ID
#
# Please make sure the default VPC security group
# for the given subnet id allows inbound SSH.
---
driver:
  name: ec2
  region: us-west-2
  instance_type: t2.micro  # AWS Free Tier
  associate_public_ip: true
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids: ["<%= ENV['AWS_SECURITY_GROUP_ID'] %>"]
  tags:
    Name: 'test-kitchen mesos-cookbook <%= Time.now.strftime("%d/%m/%Y %H:%M") %>'

busser:
  sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-7
    run_list:
      - recipe[yum]
    driver:
      image_id: ami-d2c924b2
      block_device_mappings:
        - device_name: /dev/sda1
          ebs: {volume_type: gp2, delete_on_termination: true}

suites:
  - &default
    name: 1-4-0
    run_list:
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        slave:
          flags:
            attributes: 'attribute01:value01;attribute02:value02'
  - <<: *default
    name: 1-7-0
    attributes:
      mesos:
        version: 1.7.0
